require('dotenv').config(); // Load environment variables from .env file
const express = require('express');
const fs = require('fs'); // Add fs module for reading image files
// Import the necessary classes from the library
const { GoogleGenAI, Modality } = require("@google/genai");
const path = require('path');

const app = express();
const port = process.env.PORT || 3000; // Use port from env var or default to 3000

// Ensure CORS is allowed if your frontend will be hosted separately
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', 'https://detekoi.github.io');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  
  // Handle preflight OPTIONS requests
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  next();
});

// Middleware to parse JSON bodies
app.use(express.json({ limit: '10mb' })); // Increase limit for base64 image data

// --- Gemini API Configuration ---
const API_KEY = process.env.GEMINI_API_KEY;

if (!API_KEY) {
  console.error("FATAL ERROR: GEMINI_API_KEY environment variable is not set.");
  process.exit(1); // Exit if API key is missing
}

// Add a check to ensure API_KEY is valid before initializing
if (typeof API_KEY !== 'string' || API_KEY.trim() === '') {
    console.error("FATAL ERROR: GEMINI_API_KEY is not a valid string.");
    process.exit(1);
}

// Initialize the GoogleGenAI client
const genAI = new GoogleGenAI({ apiKey: API_KEY });
// Note: With GoogleGenAI we access models directly through genAI.models

// --- Serve Static Files (HTML, CSS, JS, Images) ---
// Serve files from the parent directory where index.html is located
app.use(express.static(path.join(__dirname, '..')));

// Serve index.html for the root path specifically
// This ensures that navigating to '/' serves the main page
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'index.html'));
});

// --- Debug endpoint to list available models ---
app.get('/api/list-models', async (req, res) => {
  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${API_KEY}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    });
    
    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`REST API Error: ${response.status} - ${errorData}`);
    }
    
    const modelsData = await response.json();
    console.log('Available models:', modelsData);
    res.json(modelsData);
  } catch (error) {
    console.error('Error listing models:', error);
    res.status(500).json({
      error: 'Failed to list models',
      details: error.message
    });
  }
});

// --- Image models: Nano Banana 2 first, Nano Banana 2 Lite as fallback ---
const IMAGE_MODELS = ['gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'];

/**
 * Generate an outfit image, falling back to the next model when a model
 * errors or returns no image.
 * @param {Array} contents - Prompt and reference image parts
 * @param {Array} responseModalities - Requested output modalities
 * @returns {Promise<{imageDataUri: string, textResponse: ?string, model: string}>}
 */
async function generateOutfitImage(contents, responseModalities) {
  let lastError = null;

  for (const model of IMAGE_MODELS) {
    try {
      console.log(`Requesting image from ${model}`);
      const response = await genAI.models.generateContent({
        model,
        contents,
        config: { responseModalities }
      });

      let imageDataUri = null;
      let textResponse = null;
      const parts = response?.candidates?.[0]?.content?.parts || [];

      for (const part of parts) {
        // Gemini 3 image models may return interim "thought" parts; skip them
        if (part.thought) {
          continue;
        }
        if (part.text) {
          textResponse = part.text;
        } else if (part.inlineData) {
          console.log(`Image generated by ${model} (MIME type: ${part.inlineData.mimeType})`);
          imageDataUri = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }

      if (imageDataUri) {
        return { imageDataUri, textResponse, model };
      }
      lastError = new Error(`${model} returned no image`);
    } catch (error) {
      lastError = error;
    }
    console.warn(`Image generation failed with ${model}: ${lastError.message}`);
  }

  throw lastError;
}

// --- API Endpoint for Image Generation ---
app.post('/api/generate-image', async (req, res) => {
  // Read the original bear image from file system
  try {
    const imagePath = path.join(__dirname, '..', 'assets/images/PolarBearTransparent4K.png');
    const imageData = fs.readFileSync(imagePath);
    const base64Image = imageData.toString('base64');
    
    // Get prompt from the request, or use default
    const prompt = req.body.prompt || "Zoom out full body head-to-toe to reveal that the subject has been styled by a professional stylist, make it a cohesive theme.";
    
    console.log(`Using prompt: ${prompt.substring(0, 50)}...`);
    // Prepare the content parts for the API call
    const contents = [
      { text: prompt },
      {
        inlineData: {
          mimeType: 'image/png',
          data: base64Image
        }
      }
    ];

    const { imageDataUri, textResponse, model } = await generateOutfitImage(contents, [Modality.TEXT, Modality.IMAGE]);

    res.json({
      imageDataUri,
      textResponse,
      model
    });
    
  } catch (error) {
    console.error('Error generating/editing image with Gemini API:', error);
    res.status(500).json({
      error: 'Failed to generate/edit image',
      details: error.message
    });
  }
});

app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
  console.log("Ensure the GEMINI_API_KEY environment variable is set (e.g., via a .env file).");
});
