name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your default branch
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
      - '**/*.markdown'
      - '**/README*'
      - 'docs/**'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.html'
      - '**/*.htm'
      # Add any other content/style-only paths here

env:
  PROJECT_ID: shirokuma-fashion  # Use your actual project ID
  SERVICE_NAME: shirokuma-server
  REGION: us-west2  # Required for Gemini image generation

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: .
          env_vars: GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          flags: '--allow-unauthenticated'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}